import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  CalendarDays, CheckSquare, ClipboardList, Users, BookOpen, Bell, ChevronRight,
  Sparkles, Menu, X, Languages, Clock3, MapPin, Plus, Search, WalletCards,
  UserCheck, BarChart3, Camera, MessageCircle, Settings2, ShieldCheck, ArrowUpRight,
  CircleCheck, Circle, Megaphone, CalendarPlus, MoreHorizontal, Filter, Timer,
  Trophy, Image as ImageIcon, LayoutDashboard
} from 'lucide-react';
import './styles.css';

type Page = 'Home'|'Schedule'|'Subjects'|'Tasks'|'Exams'|'Calendar'|'Duty Wall'|'Events'|'The Weekly'|'Community'|'Study Rooms'|'Class Fund'|'Attendance'|'Members'|'Class Pulse'|'Class Moments'|'Admin Center'|'Settings';
type Lang = 'th'|'en';
type Role = 'Owner'|'Admin'|'Teacher'|'Treasurer'|'Reporter'|'Duty Manager'|'Moderator'|'Student';
type NavItem = { p: Page; icon: React.ComponentType<{size?:number;strokeWidth?:number}>; section: 'ACADEMIC'|'CLASS'|'COMMUNITY'|'MANAGEMENT' };

const items: NavItem[] = [
  {p:'Home',icon:Sparkles,section:'ACADEMIC'},{p:'Schedule',icon:CalendarDays,section:'ACADEMIC'},{p:'Subjects',icon:BookOpen,section:'ACADEMIC'},
  {p:'Tasks',icon:CheckSquare,section:'ACADEMIC'},{p:'Exams',icon:ClipboardList,section:'ACADEMIC'},{p:'Calendar',icon:CalendarDays,section:'ACADEMIC'},
  {p:'Duty Wall',icon:ClipboardList,section:'CLASS'},{p:'Events',icon:CalendarDays,section:'CLASS'},{p:'The Weekly',icon:BookOpen,section:'CLASS'},{p:'Class Moments',icon:ImageIcon,section:'CLASS'},
  {p:'Community',icon:Users,section:'COMMUNITY'},{p:'Study Rooms',icon:Timer,section:'COMMUNITY'},
  {p:'Class Fund',icon:WalletCards,section:'MANAGEMENT'},{p:'Attendance',icon:UserCheck,section:'MANAGEMENT'},{p:'Members',icon:Users,section:'MANAGEMENT'},
  {p:'Class Pulse',icon:BarChart3,section:'MANAGEMENT'},{p:'Admin Center',icon:ShieldCheck,section:'MANAGEMENT'},{p:'Settings',icon:Settings2,section:'MANAGEMENT'}
];
const navTH:Record<Page,string>={Home:'หน้าหลัก',Schedule:'ตารางเรียน',Subjects:'รายวิชา',Tasks:'งาน / การบ้าน',Exams:'การสอบ',Calendar:'ปฏิทิน','Duty Wall':'เวรประจำวัน',Events:'กิจกรรม','The Weekly':'ข่าวประจำสัปดาห์',Community:'ชุมชน','Study Rooms':'ห้องอ่านหนังสือ','Class Fund':'เงินห้อง',Attendance:'เช็กชื่อ',Members:'สมาชิก','Class Pulse':'ภาพรวมของห้อง','Class Moments':'ช่วงเวลาของห้อง','Admin Center':'ศูนย์ผู้ดูแล',Settings:'ตั้งค่า'};
const sectionTH={ACADEMIC:'วิชาการ',CLASS:'ห้องเรียน',COMMUNITY:'ชุมชน',MANAGEMENT:'การจัดการ'};
const copy={th:{program:'โครงการวิทยาศาสตร์ · 28 สมาชิก',greeting:'สวัสดีตอนเช้า, TARO.',focused:'พร้อมลุยอีกหนึ่งวัน',edit:'แก้ไขห้อง',next:'คาบเรียนถัดไป',pulse:'ภาพรวมของห้อง',forget:'อย่าลืม',view:'ดูทั้งหมด',duty:'เวรวันนี้',week:'สัปดาห์นี้',add:'+ เพิ่ม',save:'บันทึก',cancel:'ยกเลิก',search:'ค้นหา',all:'ทั้งหมด',today:'วันนี้',open:'เปิด',done:'เสร็จแล้ว',pending:'รอดำเนินการ',soon:'เร็ว ๆ นี้',members:'สมาชิก',science:'โครงการวิทยาศาสตร์'},en:{program:'SCIENCE PROGRAM · 28 MEMBERS',greeting:'GOOD MORNING, TARO.',focused:'A focused day ahead.',edit:'Edit Class',next:'NEXT CLASS',pulse:'CLASS PULSE',forget:'DON’T FORGET',view:'View all',duty:'TODAY’S DUTY',week:'THIS WEEK',add:'+ Add',save:'Save',cancel:'Cancel',search:'Search',all:'All',today:'Today',open:'Open',done:'Done',pending:'Pending',soon:'Soon',members:'members',science:'Science Program'}};

const tasks=[
 {id:1,subject:'เคมี',subjectEN:'Chemistry',title:'แบบฝึกหัดพันธะเคมี',titleEN:'Chemical Bonding worksheet',due:'พรุ่งนี้',dueEN:'Tomorrow',priority:'สูง',priorityEN:'High',done:false},
 {id:2,subject:'คณิตศาสตร์',subjectEN:'Mathematics',title:'โจทย์ชุดที่ 7',titleEN:'Problem set 7',due:'พฤหัสบดี 17 ก.ย.',dueEN:'Thu, 17 Sep',priority:'กลาง',priorityEN:'Medium',done:false},
 {id:3,subject:'ภาษาอังกฤษ',subjectEN:'English',title:'โครงร่างการนำเสนอ',titleEN:'Presentation outline',due:'ศุกร์ 18 ก.ย.',dueEN:'Fri, 18 Sep',priority:'ต่ำ',priorityEN:'Low',done:true}
];
const schedule=[['09:00','เคมี','พันธะเคมี','ห้อง 401'],['10:00','คณิตศาสตร์','ฟังก์ชัน','ห้อง 302'],['13:00','ฟิสิกส์','ปฏิบัติการ','Lab 2'],['15:00','ภาษาอังกฤษ','Presentation','ห้อง 205']];
const members=[['Taro','Owner'],['Miha','Admin'],['Aom','Reporter'],['Bank','Treasurer'],['Mild','Student'],['Poom','Student'],['Fern','Moderator'],['Boss','Student']];

function App(){
 const [page,setPage]=useState<Page>('Home'); const [open,setOpen]=useState(false); const [lang,setLang]=useState<Lang>('th'); const [query,setQuery]=useState(''); const [checked,setChecked]=useState<Record<number,boolean>>({3:true});
 const t=copy[lang]; const groups=useMemo(()=>items.reduce<Record<string,NavItem[]>>((a,x)=>{(a[x.section]??=[]).push(x); return a;},{}),[]);
 const label=(p:Page)=>lang==='th'?navTH[p]:p;
 const go=(p:Page)=>{setPage(p);setOpen(false)};
 return <div className="app">
  <aside className={open?'side open':'side'}><div className="brand"><b>CLASSROOM</b><span>OS</span><button onClick={()=>setOpen(false)}><X size={18}/></button></div>
   <button className="classMini" onClick={()=>go('Home')}><strong>6 / 1</strong><small>{t.program}</small></button>
   <nav>{Object.entries(groups).map(([s,arr])=><div key={s}><p>{lang==='th'?sectionTH[s as keyof typeof sectionTH]:s}</p>{arr.map(({p,icon:Icon})=><button key={p} className={page===p?'active':''} onClick={()=>go(p)}><Icon size={16}/><span>{label(p)}</span></button>)}</div>)}</nav>
   <footer>2026 · CLASSROOM OS</footer>
  </aside>
  <main><header><button className="menu" onClick={()=>setOpen(true)}><Menu/></button><span className="crumb">CLASSROOM OS / {label(page).toUpperCase()}</span><div className="headerActions"><div className="searchBox"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/></div><button className="langToggle" onClick={()=>setLang(lang==='th'?'en':'th')}><Languages size={15}/><b>{lang==='th'?'TH':'EN'}</b></button><Bell size={17}/><b>Taro</b></div></header>
   {page==='Home'?<Home go={go} lang={lang}/>:<PageView page={page} lang={lang} checked={checked} setChecked={setChecked}/>} 
  </main>
 </div>
}

function Home({go,lang}:{go:(p:Page)=>void;lang:Lang}){const t=copy[lang];return <div className="content home">
 <section className="hero"><div className="photo"/><div className="shade"/><div className="heroText"><small>CLASSROOM OS · 2026</small><h1>6 / 1</h1><p>{t.program}</p></div><button className="heroEdit" onClick={()=>go('Settings')}>{t.edit}</button></section>
 <section className="greet"><div><small>{lang==='th'?'วันอังคาร · 15 กันยายน':'TUESDAY · 15 SEPTEMBER'}</small><h2>{t.greeting}</h2></div><em>{t.focused}</em></section>
 <div className="topgrid"><button className="featureCard nextCard" onClick={()=>go('Schedule')}><small>{t.next}</small><h2>{lang==='th'?'เคมี':'CHEMISTRY'}</h2><p> {lang==='th'?'พันธะเคมี':'Chemical Bonding'}</p><div className="meta"><b>09:00</b> {lang==='th'?'ห้อง 401 · เริ่มใน 23 นาที':'ROOM 401 · STARTS IN 23 MIN'} <ArrowUpRight size={14}/></div></button>
 <section className="featureCard"><small>{t.pulse}</small><div className="metrics"><Metric n="8" s={lang==='th'?'กำลังเรียน':'studying'}/><Metric n="4" s={lang==='th'?'งานที่กำลังทำ':'active tasks'}/><Metric n="2" s={lang==='th'?'การสอบ':'exams'}/><Metric n="3" s={lang==='th'?'เวร':'duties'}/></div></section></div>
 <div className="split"><section><SectionHead title={t.forget} action={t.view} onClick={()=>go('Tasks')}/>{tasks.map(x=><TaskRow key={x.id} x={x} lang={lang}/>)}</section><section><SectionHead title={t.duty} action={lang==='th'?'เวรประจำวัน':'Duty Wall'} onClick={()=>go('Duty Wall')}/><article className="duty"><b>{lang==='th'?'กวาดพื้นและจัดโต๊ะ':'Sweep & arrange desks'}</b><small>Taro · 08:00</small><label>{t.pending}</label><em>{lang==='th'?'ไม้กวาดกำลังรออยู่ 👀':'The broom is waiting. 👀'}</em></article></section></div>
 <section className="week"><SectionHead title={t.week} action={lang==='th'?'ปฏิทิน':'Calendar'} onClick={()=>go('Calendar')}/><div className="timeline"><b>จันทร์ 15</b><span/>เคมี · พันธะเคมี<span/>ฟิสิกส์ · ปฏิบัติการ<span/>คณิตศาสตร์ · สอบวันศุกร์</div></section>
 </div>}
function Metric({n,s}:{n:string;s:string}){return <div><b>{n}</b><small>{s}</small></div>}
function SectionHead({title,action,onClick}:{title:string;action:string;onClick:()=>void}){return <div className="head"><h3>{title}</h3><button onClick={onClick}>{action}<ChevronRight size={14}/></button></div>}
function TaskRow({x,lang}:{x:any;lang:Lang}){return <div className="row"><i/><div><b>{lang==='th'?x.title:x.titleEN}</b><small>{lang==='th'?x.subject:x.subjectEN} · {lang==='th'?x.due:x.dueEN}</small></div><label className={x.priorityEN.toLowerCase()}>{lang==='th'?x.priority:x.priorityEN}</label></div>}

function PageView({page,lang,checked,setChecked}:{page:Page;lang:Lang;checked:Record<number,boolean>;setChecked:React.Dispatch<React.SetStateAction<Record<number,boolean>>>}){
 const title=lang==='th'?navTH[page]:page; const t=copy[lang];
 if(page==='Schedule') return <Schedule lang={lang}/>;
 if(page==='Tasks') return <Tasks lang={lang} checked={checked} setChecked={setChecked}/>;
 if(page==='Exams') return <Exams lang={lang}/>;
 if(page==='Calendar') return <CalendarPage lang={lang}/>;
 if(page==='Duty Wall') return <Duty lang={lang}/>;
 if(page==='Events') return <Events lang={lang}/>;
 if(page==='The Weekly') return <Weekly lang={lang}/>;
 if(page==='Community') return <Community lang={lang}/>;
 if(page==='Study Rooms') return <StudyRooms lang={lang}/>;
 if(page==='Class Fund') return <Fund lang={lang}/>;
 if(page==='Attendance') return <Attendance lang={lang}/>;
 if(page==='Members') return <Members lang={lang}/>;
 if(page==='Class Pulse') return <Pulse lang={lang}/>;
 if(page==='Class Moments') return <Moments lang={lang}/>;
 if(page==='Admin Center') return <Admin lang={lang}/>;
 if(page==='Settings') return <SettingsPage lang={lang}/>;
 return <div className="content"><PageTitle title={title} t={t}/><div className="empty"><Sparkles/><h2>{title}</h2><p>{lang==='th'?'โมดูลนี้พร้อมสำหรับการเชื่อมข้อมูลจริงในขั้นถัดไป':'This module is ready for real data integration in the next phase.'}</p></div></div>
}
function PageTitle({title,t}:{title:string;t:any}){return <div className="title"><div><small>CLASSROOM OS</small><h1>{title}</h1><p>6 / 1 · {t.science}</p></div><button><Plus size={15}/>{t.add}</button></div>}
function Schedule({lang}:{lang:Lang}){return <div className="content"><PageTitle title={lang==='th'?'ตารางเรียน':'Schedule'} t={copy[lang]}/><div className="days">{['จันทร์ 15','อังคาร 16','พุธ 17','พฤหัส 18','ศุกร์ 19'].map((d,i)=><button className={i===1?'selected':''} key={d}><b>{d}</b><small>{i===1?'วันนี้':''}</small></button>)}</div><div className="scheduleList">{schedule.map((s,i)=><article className="scheduleItem" key={i}><time>{s[0]}</time><div><small>{s[1]}</small><h3>{s[2]}</h3><span><MapPin size={12}/>{s[3]}</span></div><ArrowUpRight size={16}/></article>)}</div></div>}
function Tasks({lang,checked,setChecked}:{lang:Lang;checked:Record<number,boolean>;setChecked:React.Dispatch<React.SetStateAction<Record<number,boolean>>>}){return <div className="content"><PageTitle title={lang==='th'?'งาน / การบ้าน':'Tasks'} t={copy[lang]}/><div className="filterLine"><span>{lang==='th'?'ทั้งหมด 3 งาน':'3 active tasks'}</span><button><Filter size={14}/>{lang==='th'?'กรอง':'Filter'}</button></div><div className="taskList">{tasks.map(x=>{const done=!!checked[x.id];return <button className={'taskItem '+(done?'done':'')} key={x.id} onClick={()=>setChecked(v=>({...v,[x.id]:!done}))}>{done?<CircleCheck size={21}/>:<Circle size={21}/>}<div><small>{lang==='th'?x.subject:x.subjectEN}</small><b>{lang==='th'?x.title:x.titleEN}</b><span>{lang==='th'?x.due:x.dueEN}</span></div><label className={x.priorityEN.toLowerCase()}>{lang==='th'?x.priority:x.priorityEN}</label></button>})}</div></div>}
function Exams({lang}:{lang:Lang}){return <div className="content"><PageTitle title={lang==='th'?'การสอบ':'Exams'} t={copy[lang]}/><div className="examGrid"><article><small>FRI · 18 SEP</small><h2>{lang==='th'?'คณิตศาสตร์':'Mathematics'}</h2><p>{lang==='th'?'สอบปลายบท · ฟังก์ชัน':'Unit exam · Functions'}</p><strong>3 {lang==='th'?'วัน':'days'}</strong></article><article><small>MON · 21 SEP</small><h2>{lang==='th'?'เคมี':'Chemistry'}</h2><p>{lang==='th'?'พันธะเคมี':'Chemical Bonding'}</p><strong>6 {lang==='th'?'วัน':'days'}</strong></article></div><div className="notice"><Megaphone size={18}/><div><b>{lang==='th'?'เตรียมสรุป A4':'A4 cheat sheet'}</b><p>{lang==='th'?'ทบทวนพันธะโคเวเลนต์ ไอออนิก และโลหะ':'Review covalent, ionic and metallic bonding.'}</p></div></div></div>}
function Calendar({lang}:{lang:Lang}){return <div className="content"><PageTitle title={lang==='th'?'ปฏิทิน':'Calendar'} t={copy[lang]}/><div className="calendarBox"><div className="calendarHead"><button>‹</button><b>SEPTEMBER 2026</b><button>›</button></div><div className="calGrid">{['M','T','W','T','F','S','S',...Array.from({length:30},(_,i)=>String(i+1))].map((d,i)=><span className={d==='15'?'today':''} key={i}>{d}</span>)}</div></div><div className="eventStrip"><CalendarPlus/><div><b>{lang==='th'?'สอบคณิตศาสตร์':'Mathematics exam'}</b><span>18 Sep · 09:00</span></div></div></div>}
function Duty({lang}:{lang:Lang}){const rows=[['08:00','Taro','กวาดพื้นและจัดโต๊ะ','pending'],['08:00','Miha','เช็ดกระดาน','done'],['15:30','Aom','เก็บอุปกรณ์','pending'],['16:00','Bank','ตรวจห้อง','excused']];return <div className="content"><PageTitle title={lang==='th'?'เวรประจำวัน':'Duty Wall'} t={copy[lang]}/><div className="dutyBanner"><div><small>{lang==='th'?'วันนี้':'TODAY'}</small><h2>4 {lang==='th'?'หน้าที่':'duties'}</h2></div><span>{lang==='th'?'Friendly Humor Mode':'Friendly Humor Mode'} · ON</span></div><div className="dutyList">{rows.map((r,i)=><article key={i}><time>{r[0]}</time><div><b>{r[1]}</b><p>{r[2]}</p></div><label className={r[3]}>{r[3]==='done'?(lang==='th'?'เสร็จแล้ว':'Done'):r[3]==='excused'?(lang==='th'?'ได้รับยกเว้น':'Excused'):(lang==='th'?'รอดำเนินการ':'Pending')}</label><MoreHorizontal size={16}/></article>)}</div></div>}
function Events({lang}:{lang:Lang}){return <div className="content"><PageTitle title={lang==='th'?'กิจกรรม':'Events'} t={copy[lang]}/><div className="eventHero"><div><small>UPCOMING</small><h2>{lang==='th'?'ทัศนศึกษา · ศูนย์วิทยาศาสตร์':'Science Center field trip'}</h2><p>22 SEP · 08:30 — 15:30</p></div><button><CalendarPlus size={15}/> RSVP</button></div><div className="eventCards"><article><small>19 SEP</small><b>{lang==='th'?'ประชุมกลุ่มโครงงาน':'Project group meeting'}</b><span>16:00 · Library</span></article><article><small>25 SEP</small><b>{lang==='th'?'วันกีฬาสี':'Sports day'}</b><span>07:30 · School field</span></article></div></div>}
function Weekly({lang}:{lang:Lang}){return <div className="content"><div className="weeklyCover"><small>THE 6 / 1 WEEKLY · ISSUE 04</small><h1>{lang==='th'?'สัปดาห์นี้ในห้อง 6 / 1':'THIS WEEK IN 6 / 1'}</h1><p>15 — 20 SEP 2026</p></div><div className="weeklyGrid"><article><small>ACADEMIC</small><h2>{lang==='th'?'สัปดาห์แห่งพันธะเคมี':'The week of Chemical Bonding'}</h2><p>{lang==='th'?'งานเคมี 1 ชิ้น และสอบคณิตศาสตร์ในวันศุกร์':'One chemistry worksheet and a mathematics exam on Friday.'}</p></article><article><small>CLASS</small><h2>{lang==='th'?'4 เวร · 2 กิจกรรม':'4 duties · 2 events'}</h2><p>{lang==='th'?'เตรียมทีมสำหรับกิจกรรมปลายสัปดาห์':'Prepare teams for the end-of-week activities.'}</p></article></div></div>}
function Community({lang}:{lang:Lang}){return <div className="content"><PageTitle title={lang==='th'?'ชุมชน':'Community'} t={copy[lang]}/><div className="channelLayout"><aside><b>CHANNELS</b>{['ทั่วไป','การบ้าน','ประกาศ','โครงงาน'].map((x,i)=><button className={i===0?'selected':''} key={x}><MessageCircle size={14}/>{lang==='th'?x:['general','homework','announcements','projects'][i]}</button>)}</aside><section className="chat"><div className="chatHead"><div><b># {lang==='th'?'ทั่วไป':'general'}</b><small>28 {t.members}</small></div><button>⋯</button></div>{[['Miha','พรุ่งนี้มีประชุมกลุ่มนะ'],['Aom','ใครมีโน้ตฟิสิกส์บ้าง?'],['Taro','อัปไว้ใน Files แล้ว']].map((m,i)=><div className="message" key={i}><div className="avatar">{m[0][0]}</div><div><b>{m[0]}</b><p>{m[1]}</p><small>10:{20+i*7}</small></div></div>)}<div className="composer"><input placeholder={lang==='th'?'เขียนข้อความ…':'Write a message…'}/><button><ArrowUpRight size={16}/></button></div></section></div></div>}
function StudyRooms({lang}:{lang:Lang}){return <div className="content"><PageTitle title={lang==='th'?'ห้องอ่านหนังสือ':'Study Rooms'} t={copy[lang]}/><div className="roomGrid"><article className="room activeRoom"><div className="live"><span/>LIVE</div><small>ROOM 01</small><h2>{lang==='th'?'เคมี · พันธะเคมี':'Chemistry · Chemical Bonding'}</h2><div className="timer">42:18</div><p>6 {lang==='th'?'คนกำลังโฟกัส':'people focused'}</p><button><Timer size={15}/> {lang==='th'?'เข้าห้อง':'Join room'}</button></article><article className="room"><small>ROOM 02</small><h2>{lang==='th'?'คณิตศาสตร์':'Mathematics'}</h2><div className="timer">25:00</div><p>3 {lang==='th'?'คน':'people'}</p><button>{lang==='th'?'ดูห้อง':'View room'}</button></article><article className="room"><small>ROOM 03</small><h2>{lang==='th'?'อ่านเงียบ':'Quiet study'}</h2><div className="timer">50:00</div><p>1 {lang==='th'?'คน':'person'}</p><button>{lang==='th'?'ดูห้อง':'View room'}</button></article></div></div>}
function Fund({lang}:{lang:Lang}){return <div className="content"><PageTitle title={lang==='th'?'เงินห้อง':'Class Fund'} t={copy[lang]}/><div className="fundTop"><article><small>{lang==='th'?'ยอดคงเหลือ':'BALANCE'}</small><strong>฿ 8,420</strong><span>+฿ 1,500 {lang==='th'?'เดือนนี้':'this month'}</span></article><article><small>{lang==='th'?'ค้างจ่าย':'OUTSTANDING'}</small><strong>฿ 320</strong><span>2 {lang==='th'?'คน':'members'}</span></article></div><div className="ledger"><div className="head"><h3>{lang==='th'?'รายการล่าสุด':'Recent activity'}</h3><button>{lang==='th'?'ดูทั้งหมด':'View all'}</button></div>{[['+','เก็บเงินห้อง','฿ 1,500'],['−','อุปกรณ์โครงงาน','฿ 620'],['−','กระดาษพิมพ์','฿ 180'],['+','คืนเงินกิจกรรม','฿ 300']].map((r,i)=><div className="ledgerRow" key={i}><b className={r[0]==='+'?'plus':'minus'}>{r[0]}</b><span>{r[1]}</span><strong>{r[2]}</strong></div>)}</div></div>}
function Attendance({lang}:{lang:Lang}){return <div className="content"><PageTitle title={lang==='th'?'เช็กชื่อ':'Attendance'} t={copy[lang]}/><div className="attendanceHero"><div><small>{lang==='th'?'วันนี้ · 15 กันยายน':'TODAY · 15 SEPTEMBER'}</small><h2>26 / 28</h2><p>{lang==='th'?'มาเรียน':'present'} · 92.9%</p></div><div className="qr"><div>QR</div><small>{lang==='th'?'สแกนเพื่อเช็กชื่อ':'Scan to check in'}</small></div></div><div className="peopleList">{members.slice(0,6).map((m,i)=><div key={i}><span className="avatar">{m[0][0]}</span><b>{m[0]}</b><label className={i===2?'late':'present'}>{i===2?(lang==='th'?'สาย':'Late'):(lang==='th'?'มา':'Present')}</label></div>)}</div></div>}
function Members({lang}:{lang:Lang}){return <div className="content"><PageTitle title={lang==='th'?'สมาชิก':'Members'} t={copy[lang]}/><div className="memberToolbar"><div className="searchBox"><Search size={14}/><input placeholder={copy[lang].search}/></div><button><Plus size={15}/> {lang==='th'?'เชิญสมาชิก':'Invite'}</button></div><div className="memberGrid">{members.map((m,i)=><article key={i}><span className="avatar big">{m[0][0]}</span><div><h3>{m[0]}</h3><p>{m[1]}</p></div><button>⋯</button></article>)}</div></div>}
function Pulse({lang}:{lang:Lang}){return <div className="content"><PageTitle title={lang==='th'?'ภาพรวมของห้อง':'Class Pulse'} t={copy[lang]}/><div className="pulseGrid"><article><small>{lang==='th'?'งานเสร็จตรงเวลา':'ON-TIME TASKS'}</small><strong>82%</strong><div className="bar"><i style={{width:'82%'}}/></div></article><article><small>{lang==='th'?'การเข้าเรียน':'ATTENDANCE'}</small><strong>93%</strong><div className="bar"><i style={{width:'93%'}}/></div></article><article><small>{lang==='th'?'การมีส่วนร่วม':'ENGAGEMENT'}</small><strong>76%</strong><div className="bar"><i style={{width:'76%'}}/></div></article></div><div className="pulseNote"><BarChart3/><div><b>{lang==='th'?'ห้องกำลังไปได้ดี':'Class is moving well'}</b><p>{lang==='th'?'จุดที่ควรจับตาคือการส่งงานวิชาเคมี':'The main watchpoint is chemistry task completion.'}</p></div></div></div>}
function Moments({lang}:{lang:Lang}){return <div className="content"><PageTitle title={lang==='th'?'ช่วงเวลาของห้อง':'Class Moments'} t={copy[lang]}/><div className="moments"><div className="moment feature"><div className="fakePhoto">FIELD<br/>DAY</div><div><small>12 SEP 2026</small><h2>{lang==='th'?'วันทดลองวิทยาศาสตร์':'Science experiment day'}</h2><p>6 / 1 · 14 photos</p></div></div>{['Lab session','After class','Project prep','Class photo'].map((x,i)=><article key={x}><div className="fakeThumb">{String(i+1).padStart(2,'0')}</div><small>SEP {10+i}</small><b>{lang==='th'?['เข้าห้องแล็บ','หลังเลิกเรียน','เตรียมโครงงาน','รูปห้อง'][i]:x}</b></article>)}</div></div>}
function Admin({lang}:{lang:Lang}){const sections=lang==='th'?['สมาชิกและสิทธิ์','จัดการวิชาการ','จัดการเวร','การเงิน','ชุมชน','กิจกรรม','เช็กชื่อ','สื่อและแกลเลอรี','บันทึกกิจกรรม','การตั้งค่าห้อง']:['Members & Roles','Academic Manager','Duty Manager','Finance Center','Community Manager','Events & Activities','Attendance','Media Gallery','Activity Logs','Class Settings'];return <div className="content"><PageTitle title={lang==='th'?'ศูนย์ผู้ดูแล':'Admin Center'} t={copy[lang]}/><div className="adminIntro"><ShieldCheck/><div><b>{lang==='th'?'Owner Access':'Owner Access'}</b><p>{lang==='th'?'คุณสามารถจัดการข้อมูลและสิทธิ์ทั้งหมดของห้องนี้':'You can manage all classroom data and permissions.'}</p></div><span>OWNER</span></div><div className="adminGrid">{sections.map((s,i)=><button key={s}><span>{['Users','BookOpen','ClipboardList','WalletCards','MessageCircle','CalendarDays','UserCheck','ImageIcon','LayoutDashboard','Settings2'][i]}</span><div><b>{s}</b><small>{lang==='th'?'จัดการและตรวจสอบ':'Manage and review'}</small></div><ChevronRight size={16}/></button>)}</div></div>}
function SettingsPage({lang}:{lang:Lang}){const rows=lang==='th'?[['ภาษา','ไทย / English'],['ธีมห้อง','Sage'],['Classroom Humor Mode','Friendly'],['Public Duty Status','เปิด'],['Allow Duty Swap','เปิด'],['รูปปกห้อง','เปลี่ยนรูป']]:[['Language','Thai / English'],['Class Theme','Sage'],['Classroom Humor Mode','Friendly'],['Public Duty Status','ON'],['Allow Duty Swap','ON'],['Class Cover','Change photo']];return <div className="content"><PageTitle title={lang==='th'?'ตั้งค่า':'Settings'} t={copy[lang]}/><div className="settingsCard">{rows.map((r,i)=><div key={i}><span>{r[0]}</span><button>{r[1]}<ChevronRight size={15}/></button></div>)}</div><div className="dangerNote"><b>{lang==='th'?'การควบคุมข้อมูล':'Data control'}</b><p>{lang==='th'?'สิทธิ์ Owner ถูกตรวจสอบฝั่งเซิร์ฟเวอร์เมื่อเชื่อม Supabase':'Owner permissions will be enforced server-side when Supabase is connected.'}</p></div></div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
